# rustic config file to backup /home, /etc and /root to a hot/cold repository hosted by OVH
# using OVH cloud archive and OVH object storage
#
# backup usage: "rustic -P ovh-hot-cold backup
# cleanup:      "rustic -P ovh-hot-cold forget --prune
#
[repository]
repository = "rclone:ovh:backup-home"
repo-hot = "rclone:ovh:backup-home-hot"
password-file =  "/root/key-rustic-ovh"
cache-dir = "/var/lib/cache/rustic" # explicitly specify cache dir for remote repository 
warm-up = true # cold storage needs warm-up, just trying to access a file is sufficient to start the warm-up
warm-up-wait = "10m" # in my examples, 10 minutes wait-time was sufficient, according to docu it can be up to 12h

[forget]
keep-daily = 8
keep-weekly = 5
keep-monthly = 13
keep-yearly = 10

[backup]
exclude-if-present = [".nobackup", "CACHEDIR.TAG"]
glob-file = ["/root/rustic-ovh.glob"]
one-file-system = true

[[backup.sources]]
source = "/home"
git-ignore = true

[[backup.sources]]
source = "/etc"

[[backup.sources]]
source = "/root"
